---
- name: Set SELinux to Permissive
  become: yes
  selinux:
    policy: targeted
    state: permissive

- name: Disable Swap
  become: yes
  command: swapoff --all
  ignore_errors: yes

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Copy Kubernetes Repo File
  become: yes
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Install Kubernetes
  become: yes
  yum: 
    name: ['kubelet-{{ kube_version }}', 'kubectl-{{ kube_version }}', 'kubeadm-{{ kube_version }}']
    state: installed

- name: Copy k8s.conf
  become: yes
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Create .kube directory
  file:
    path: "/home/{{ user }}/.kube"
    state: directory
    mode: 0700

- name: Enable and Start Kubelet
  become: yes
  service:
    name: "kubelet"
    enabled: yes
    state: started

- name: Pass bridged IPv4 traffic to iptables
  become: yes
  shell: >
    sysctl net.bridge.bridge-nf-call-iptables=1

- name: Pass bridged IPv6 traffic to iptables
  become: yes
  shell: >
    sysctl net.bridge.bridge-nf-call-ip6tables=1

- name: Refresh Kernel Settings
  become: yes
  shell: >
    sysctl --system

- name: Install Bash Completion
  become: yes
  yum:
    name: bash-completion
    state: installed

- name: Add Kubectl Bash Completion
  lineinfile:
    path: "/home/{{ user }}/.bashrc"
    line: 'source <(kubectl completion bash)'
    insertbefore: EOF
