---
- name: Set SELinux to Permissive
  become: yes
  selinux:
    policy: targeted
    state: permissive

- name: Disable Swap
  become: yes
  command: swapoff --all
  ignore_errors: yes

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Copy Kubernetes Repo File
  become: yes
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Install Kubernetes
  become: yes
  yum: 
    name: "{{ item }}-{{ kube_version}}"
    state: installed
  with_items:
  - kubelet
  - kubectl
  - kubeadm

- name: Copy k8s.conf
  become: yes
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Create .kube directory
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: 0700

- name: Enable and Start Kubelet
  become: yes
  service:
    name: "kubelet"
    enabled: yes
    state: started

- name: Pass bridged IPv4 traffic to iptables
  become: yes
  shell: >
    sysctl net.bridge.bridge-nf-call-iptables=1

- name: Pass bridged IPv6 traffic to iptables
  become: yes
  shell: >
    sysctl net.bridge.bridge-nf-call-ip6tables=1

- name: Refresh Kernel Settings
  become: yes
  shell: >
    sysctl --system

- name: Install Gluster Dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - epel-release
  - centos-release-gluster

- name: Install Gluster
  become: yes
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - glusterfs
  - glusterfs-cli
  - glusterfs-fuse
  - glusterfs-server
  - heketi-client
