---
- name: Copy Flannel
  become: yes
  copy:
    src: files/flannel.yml
    dest: "/home/{{ user }}/flannel.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  when: overlay == 'flannel'

- name: Apply Flannel Overlay
  command: "kubectl apply -f /home/{{ user }}/flannel.yml"
  args:
    creates: /etc/.overlay
  when: overlay == 'flannel'

- name: Block Overlay
  become: yes
  command: touch /etc/.overlay
  when: overlay == 'flannel'
