---
- name: Ensure Correct cGroup
  become: yes
  lineinfile:
    dest: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    state: present
    regexp: '^Environment="KUBELET_KUBECONFIG_ARGS='
    line: 'Environment="KUBELET_KUBECONFIG_ARGS=--cgroup-driver=systemd --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"'
  when: overlay == 'flannel'

- name: Restart Kubelet
  become: yes
  service:
    name: "kubelet"
    state: restarted

- name: Run kubeadm init with Weave Overlay
  become: yes
  command: kubeadm init --token={{ kube_token }} --apiserver-advertise-address={{ kube_advertise }} --ignore-preflight-errors=NumCPU
  args:
    creates: /etc/.kubeadminit
  when: overlay == 'weave'

- name: Run kubeadm init with Flannel Overlay
  become: yes
  command: kubeadm init --token={{ kube_token }} --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ kube_advertise }} --ignore-preflight-errors=NumCPU
  args:
    creates: /etc/.kubeadminit
  when: overlay == 'flannel' 

- name: Block kubeadm init
  become: yes
  command: touch /etc/.kubeadminit

- name: Copy Kubeconfig To Home
  become: yes
  command: cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config

- name: Setup Config Permissions
  become: yes
  file:
    path: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Get Kubectl Version
  shell: kubectl version | base64 | tr -d '\n'
  register: kubectl_version
